# Site settings
title: "Chelonian Access Documentation"
description: >-
  Modern, modular RFID Access System
baseurl: "/chelonian-access"
url: "https://dapperdivers.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Enable search
search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Footer content
footer_content: "Copyright &copy; 2025 DapperDivers. MIT License."

# External links
aux_links:
  "GitHub Repository":
    - "//github.com/dapperdivers/chelonian-access"

# Navigation structure
nav_order_separator: 1000

# Collections for better organization
collections:
  features:
    permalink: "/:collection/:path/"
    output: true
  development:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    features:
      name: Feature Guides
      nav_order: 4
    development:
      name: Development
      nav_order: 5
