# Site settings
title: "Chelonian Access"
description: >-
  Modern, modular RFID Access System
baseurl: "/chelonian-access"
url: "https://dapperdivers.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs
color_scheme: light

# Enable search
search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Footer content
footer_content: "Copyright &copy; 2025 DapperDivers. MIT License."

# External links
aux_links:
  "GitHub Repository":
    - "//github.com/dapperdivers/chelonian-access"

# Navigation structure
nav_order_separator: 1000

# Collections for better organization
collections:
  guides:
    permalink: "/:collection/:path/"
    output: true
  features:
    permalink: "/:collection/:path/"
    output: true

# Navigation Configuration
just_the_docs:
  collections:
    guides:
      name: Guides
      nav_order: 4
    features:
      name: Features
      nav_fold: true  # This will make the features section collapsible
      nav_order: 5

# Default front matter settings
defaults:
  -
    scope:
      path: ""
      type: "guides"
    values:
      layout: "page"
      parent: "Guides"
  -
    scope:
      path: ""
      type: "features"
    values:
      layout: "page"
      parent: "Features"
